# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:

  # ---------------------------------------------------------------------------------- Style Rules
  # Rules to maintain a consistent and readable code style.

  # Enforce single quotes for strings.
  prefer_single_quotes: true

  # Always place required named parameters first in constructors.
  always_put_required_named_parameters_first: true

  # Enforce curly braces for all flow control structures.
  curly_braces_in_flow_control_structures: true

  # Prefer using `final` for local variables that are not reassigned.
  prefer_final_locals: true

  # Sort `child` properties last in widget constructors for better readability.
  sort_child_properties_last: true

  # Avoid unnecessary braces in string interpolations.
  unnecessary_brace_in_string_interps: true

  # Avoid using `this` when it is not necessary.
  unnecessary_this: true

  # Use absolute package imports for files in `lib/` to avoid broken imports.
  always_use_package_imports: true

  # ---------------------------------------------------------------------------- Performance Rules
  # Rules to help improve application performance.

  # Prefer `const` constructors where possible for performance optimization.
  prefer_const_constructors: true

  # Prefer `const` declarations for variables that can be constant.
  prefer_const_declarations: true

  # ---------------------------------------------------------- Clean Code & Error Prevention Rules
  # Rules for cleaner, more readable, and less error-prone code.

  # Avoid using `print()`. Use a dedicated logger in a real application.
  avoid_print: true

  # Avoid initializing variables to null when they can be declared without an initial value.
  avoid_init_to_null: true

  # Avoid providing redundant default values for parameters.
  avoid_redundant_argument_values: true

  # Avoid returning null for a function with a `void` return type.
  avoid_returning_null_for_void: true

  # Prevent reassigning values to method parameters.
  parameter_assignments: true

  # Prefer using the cascade operator (`..`) for consecutive method calls on the same object.
  cascade_invocations: true

  # Prefer function declarations over variables holding a function literal.
  prefer_function_declarations_over_variables: true

  # Prefer using `isEmpty` and `isNotEmpty` over checking `length`.
  prefer_is_empty: true
  prefer_is_not_empty: true

  # Avoid unnecessary null checks.
  unnecessary_null_checks: true

  # Do not use leading underscores for local identifiers, as it has no effect on privacy.
  no_leading_underscores_for_local_identifiers: true

  # ----------------------------------------------------------------------- Flutter Specific Rules
  # Rules that are specific to Flutter development best practices.

  # Avoid using `BuildContext` across asynchronous gaps.
  use_build_context_synchronously: true

  # Always use `Key` in widget constructors.
  use_key_in_widget_constructors: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
